name: "Android Build"
on: [push]

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek (Checkout)
        uses: actions/checkout@v4 # v4 sürümüne güncellendi
        with:
          lfs: true

      - name: Godot Kurulumu
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.2.1

      - name: Android APK Oluştur
        run: |
          mkdir -v -p build/android
          # Headless modda Godot'yu çalıştırıp APK alıyoruz
          godot --headless --export-release "Android" build/android/oyun.apk
          
      - name: APK Dosyasını Yükle (Artifact)
        uses: actions/upload-artifact@v4 # HATAYI ÇÖZEN GÜNCELLEME BURASI
        with:
          name: Oyun-Paketi
          path: build/android/oyun.apk
          retention-days: 5 # Dosyanın 5 gün sonra silinmesini sağlar (yer kaplamaz)
