name: "Android Build"
on: [push]

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Godot Kurulumu (Standard Version)
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.2.1
          use-mono: false # C# kullanmadığımız için kapattık

      - name: Export Sablonlarini İndir
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.2.1.stable
          wget https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          unzip Godot_v4.2.1-stable_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/4.2.1.stable/

      - name: Android APK Olustur
        run: |
          mkdir -p build/android
          godot --headless --export-release "Android" build/android/oyun.apk
          
      - name: APK Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Oyun-Paketi
          path: build/android/oyun.apk
