name: "Android Build - Keystore Fix"
on: [push]

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Godot Standart Indir
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          unzip Godot_v4.2.1-stable_linux.x86_64.zip
          mv Godot_v4.2.1-stable_linux.x86_64 godot
          chmod +x godot

      - name: Export Sablonlarini Kur
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/4.2.1.stable
          wget https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          unzip Godot_v4.2.1-stable_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/4.2.1.stable/

      - name: Android SDK Ayari
        uses: android-actions/setup-android@v3

      - name: Debug Keystore Olustur
        run: |
          # Anahtarı direkt ana dizinde oluşturuyoruz
          keytool -keyalg RSA -genkey -v -keystore debug.keystore -alias androiddebugkey -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999
          ls -l debug.keystore # Dosya oluştu mu kontrol et (loglarda göreceğiz)

      - name: APK Olustur
        run: |
          mkdir -p build/android
          # Export komutu
          ./godot --headless --verbose --export-release "Android" build/android/oyun.apk
          
      - name: APK Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Oyun-Paketi
          path: build/android/oyun.apk
